---
title: "Project2"
output: html_notebook
---

```{r}
#load in packages
#install.packages("segmented")
library(jsonlite)
library(tidyverse)
library(dplyr)
library(plyr)
library(data.table)
library(ggplot2)
library(scales)
library(segmented)

#load in datasets
data0<-read_json("A://1.geojson")
data1<-read_json("A://2.geojson")
data2<-read_json("A://3.geojson")
data3<-read_json("A://4.geojson")
data4<-read_json("A://5.geojson")
data5<-read_json("A://6.geojson")
data6<-read_json("A://7.geojson")
data7<-read_json("A://8.geojson")
data8<-read_json("A://9.geojson")
data9<-read_json("A://10.geojson")
data10<-read_json("A://11.geojson")
```
```{r}
data<-c(data0$features,data1$features,data2$features,data3$features,data4$features,data5$features,data7$features,data8$features,data9$features,data10$features)
databak<-data
timestamps<-NA
for (i in 1:length(data)){
  timestamps[i]<-data[[i]]$properties$time
}
long<-NA
for (i in 1:length(data)){
  long[i]<-unlist(data[[i]]$geometry$coordinates[1])
}
lat<-NA
for (i in 1:length(data)){
  lat[i]<-unlist(data[[i]]$geometry$coordinates[2])
}
timelong<-NA
for (i in 1:length(data)){
  timelong[i]<-((data[[i]]$properties$time_long/1000)-21600) #convert ms to seconds, then convert it to "Montana UNIX" time
}
data<-data.frame(long,lat,timestamps,timelong)

days<-c(rep(1,length(data0$features)),rep(2,length(data1$features)),rep(3,length(data2$features)),rep(4,length(data3$features)),rep(5,length(data4$features)),rep(1,length(data5$features)),rep(3,length(data7$features)),rep(4,length(data8$features)),rep(4,length(data9$features)),rep(5,length(data10$features)))

dayinfo<-data.frame(dayn=1:5,dayc=c("Tuesday","Wednesday","Thursday","Friday","Monday"))

sessions<-c(rep(1,length(data0$features)),rep(2,length(data1$features)),rep(3,length(data2$features)),rep(4,length(data3$features)),rep(5,length(data4$features)),rep(6,length(data5$features)),rep(7,length(data7$features)),rep(8,length(data8$features)),rep(9,length(data9$features)),rep(10,length(data10$features)))

data<-cbind(data,sessions,days)
```

```{r}
#preliminary visualizations
plot(data$long,data$lat,main="First 10 Datapoints",ylab="lat",xlab="long")
plot(data$long[1:4535],data$lat[1:4535],main="First 10 Datapoints",ylab="lat",xlab="long")

plot(density(data$days))#day distribution #we want to place bomb on Monday or on Friday.

plot(data[data$sessions==8,]$timelong,data[data$sessions==8,]$lat) #throw this out
plot(data[data$sessions==8,]$timelong,data[data$sessions==8,]$long)

plot(data[data$sessions==7&data$timelong<1598560000,]$lat,data[data$sessions==7&data$timelong<1598560000,]$long) #time units
plot(data[data$sessions==7&data$timelong<1598530000,]$timelong,data[data$sessions==7&data$timelong<1598530000,]$long)
plot(data[data$sessions==7&data$timelong<1598535000,]$timelong,data[data$sessions==7&data$timelong<1598535000,]$lat)
plot((data[data$sessions==10,]$long),(data[data$sessions==10,]$lat))
plot(data$lat,data$long)

data<-data[!data$sessions==8,]
#for (i in c(1,2,3,4,5,7,9,10)){
  #order(data[data$sessions==i,])
#}
#now sort data frame according to UNIX time in ascending order.
sortr<-function(x){
 return(x[order(timelong),])
}
data<-na.omit(data[order(timelong),])

plot(density(data$days))#bomb on Monday.

```

```{r}
#more visualizations
length(data1$features)
plot(data[data$sessions==10,]$timelong,data[data$sessions==10,]$lat) #train the data with only the first leg of the trip, and bomb him
plot(data[data$sessions==10,]$timelong,data[data$sessions==10,]$long)
#convert time to time elapsed since 12:00AM every day.
#test conversion
print(data$timestamps[1]) #subtract 6 from this time to get Montana time
((data$timelong[1])%%86400)/(60*60)
#convert all
elapsed<-NA
for (i in 1:dim(data)[1]){
  elapsed[i]<-((data$timelong[i])%%86400)
}
data<-cbind(data,elapsed)
tail(data)
```
```{r}
#reduce the dataset to only include first legs for each daily sessions
d<-list()
for (i in 1:10){
  d[[i]]<-mutate(.data=data[data$sessions==i,],diff=elapsed-lag(elapsed),diffsum=elapsed-first(elapsed)) #also add time elapsed since departure in anticipation of the kriging estimatation of time since departure.
}
d[[8]]<-NULL
for (i in 1:9){
  d[[i]]<-d[[i]][1:(which(d[[i]]$diff>1000))-1,]
}
data<-do.call("rbind",d)
#check that only first legs are in
plot(data[data$sessions==2,]$timelong,data[data$sessions==2,]$long)
plot(data[data$sessions==1,]$lat,data[data$sessions==1,]$nextlat)
plot(data[data$sessions==1,]$lat,data[data$sessions==1,]$nextlat)
data[data$sessions==1,]$lat
data[is.na(data)]<-0



```

```{r}
a<-as.vector(table(data$sessions))
#staggered layering to prepare for iterative regression 
nextlong<-c(data$long,NA)
nextlat<-c(data$lat,NA)
data<-rbind(NA,data)
data<-na.omit(cbind(data,nextlong,nextlat))
data[a,]$nextlong<-NA
data[a,]$nextlat<-NA
data[c(76:82),]
```
```{r}
#First step model: iterative regression of latitude split by day
data$days<-as.factor(data$days)
iterator<-function(x){
  l<-list()
  l[[1]]<-lm(nextlat~lat,data=x[x$lat<46.87000,])
  l[[2]]<-lm(nextlat~lat,data=x[x$lat>46.87000,])
  return(l)
}
ir<-dlply(data,.(days),iterator)
#uncheck to see the sample regression outputs and robustness check plots

#Second step model: segmented MLR on longitude split by day

#plots to determine if piece-wise regression can help
ggplot(data,aes(x=lat,y=long))+
  geom_point()+
  stat_smooth(method = 'lm')+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 20)) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10))
ggplot(data,aes(x=lat,y=long))+
  geom_point()+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10))+
  stat_smooth(data=subset(data,lat<46.8653),method = 'lm')+
  stat_smooth(data=subset(data,lat>=46.8653&lat<46.8683),method = 'lm',col="red")+
  stat_smooth(data=subset(data,lat>=46.8683&lat<46.8750),method = 'lm')+
  stat_smooth(data=subset(data,lat>=46.8750&lat<46.8850),method = 'lm')+
  stat_smooth(data=subset(data,lat>=46.8850),method = 'lm')
ggplot(data,aes(x=long,y=lat))+
  geom_point()
#demonstrate weakness of regressing the entire dataset
model<-lm(long~lat+diffsum,data=data)
summary(model)
#conduct piece-regression, by day of the week.
bp=c(46.8653,46.8683,46.8750,46.8850) #define breaking points
#define function that returns regressions separated by breaking points.
segmentr<-function(x){
  l<-list()
  l[[1]]<-(lm(long~lat,data=x[x$lat<bp[1],]))
  l[[2]]<-(lm(long~lat,data=x[x$lat>=bp[1]&x$lat<bp[2],]))
  l[[3]]<-(lm(long~lat,data=x[x$lat>=bp[2]&x$lat<bp[3],]))
  l[[4]]<-(lm(long~lat,data=x[x$lat>=bp[3]&x$lat<bp[4],]))
  l[[5]]<-(lm(long~lat,data=x[x$lat>=bp[4],]))
  return(l)
}
mlr<-dlply(data,.(days),segmentr)
print(dayinfo)
```

```{r}
#fourth step function: show day of week
dayrdr<-function(x){
  a<-x[[2]][[1]]$properties$time
  if(as.POSIXlt(a)$wday==1){
    d<-as.POSIXlt(a)$wday+4
  }
  else{
  d<-as.POSIXlt(a)$wday-1
  }
  return(d)
}
dayconvt<-function(x){
  d<-data.frame(dayn=1:5,dayc=c("Tuesday","Wednesday","Thursday","Friday","Monday"))
  a<-d[x,2]
  return(a)
}
```

```{r}
#predicting algorithm
#reload dependencies
library(jsonlite)
library(tidyverse)
library(dplyr)
library(plyr)
library(data.table)
library(ggplot2)
library(scales)
library(fields)
#testdata<-read_json("PUT IN FILE DIRECTORY of TESTING DATA HERE")
#trainingdata<-read.csv("PUT IN FILE DIRECTORY of the PROVIDED TRAINING DATA HERE")
trainingdata<-read.csv("A://trainingdata.csv")
testdata<-read_json("A://test1.geojson")
#get the day of the week
day<-dayrdr(testdata)
#get the initial latitude 
latt<-unlist(testdata[[2]][[1]]$geometry$coordinates[[2]])
#get the initial longitude
longt<-unlist(testdata[[2]][[1]]$geometry$coordinates[[1]])
#function that predicts latitude given initial latitude
latgtr<-function(x){
    n<-1
    latvec<-NA
    unc<-list()
    latvec[n]<-predict(ir[[day]][[1]],data.frame(lat=x))
    while (latvec[n]<46.8700){
      latvec[n+1]<-predict(ir[[day]][[1]],data.frame(lat=latvec[n]))
      unc[[n+1]]<-predict(ir[[day]][[1]],data.frame(lat=latvec[n]),interval="prediction")
      n<-n+1
    }
    while (latvec[n]>46.85860){
      latvec[n+1]<-predict(ir[[day]][[2]],data.frame(lat=latvec[n]))
      unc[[n+1]]<-predict(ir[[day]][[1]],data.frame(lat=latvec[n]),interval="prediction")
      n<-n+1
    }
    return(do.call("rbind",unc))
}
predlat<-latgtr(latt) #store predicted latitudes and their intervals 
#function that predicts longitudes given predicted latitudes
longgtr<-function(x,d){
  bp=c(46.8653,46.8683,46.8750,46.8850)
  unc<-list()
  for (i in 1:length(x)){
    if (x[i]<bp[1]){
    unc[[i]]<-predict(mlr[[d]][[1]],data.frame(lat=x[i]),interval="prediction")
    }
    if (x[i]>=bp[1]&x[i]<bp[2]){
    unc[[i]]<-predict(mlr[[d]][[2]],data.frame(lat=x[i]),interval="prediction")
    }
    if (x[i]>=bp[2]&x[i]<bp[3]){
    unc[[i]]<-predict(mlr[[d]][[3]],data.frame(lat=x[i]),interval="prediction")
    }
    if (x[i]>=bp[3]&x[i]<bp[4]){
    unc[[i]]<-predict(mlr[[d]][[4]],data.frame(lat=x[i]),interval="prediction")
    }
    if (x[i]>=bp[4]){
    unc[[i]]<-predict(mlr[[d]][[5]],data.frame(lat=x[i]),interval="prediction")
    }
  }
  return(do.call("rbind",unc))
}
#store predicted longitudes and intervals
predlong<-longgtr(predlat[,1],day)
#form a data frame of predicted values
predcoord<-data.frame(predictedlat=predlat[,1],predictedlong=predlong[,1])
#form a data frame of predicted values with intervals
predall<-cbind(predlat,predlong)
predall<-as.data.frame(predall)
colnames(predall)<-c("latfit","lwerlat","uprlat","longfit","lwerlong","uprlong")

# KNN function to predict time elapsed since departure, using latitude as a predictor.
  knn<- function(xn,k = 5,x,y){
  n <- length(x)
  stopifnot(length(x) == n, length(y) == n,
  length(xn) == 1, k <= n)
  dists <- sqrt((x-xn)^2)
  neighbors <- order(dists)[1:k]
  neighb.out <- y[neighbors]
  return(mean(neighb.out))
  }
  #fill in time since departure
timesincedpt<-NA
for (i in 1:dim(predall)[1]){
  timesincedpt[i]<-knn(predall$latfit[i],x=trainingdata$lat,y=trainingdata$diffsum)
}
predall<-as.data.frame(cbind(predall,timesincedpt))
#filter first 5 minutes of travel
predall<-predall[predall$timesincedpt>300,]
for (i in 1:dim(predall)[1]-1){
  predall$dist[i]<-as.numeric(rdist.earth(predall[i,c(4,1)],predall[i+1,c(4,1)],miles = T))
  predall$timediff[i]<-abs(predall[i+1,7]-predall[i,7])
}
#filter stationary points, stationary defined as movement less then ~10m in over 2 minutes
for (i in 1:dim(predall)[1]-1){
if (predall[i+1,]$dist<0.001864&predall[i+1,]$timediff>120){
  predall[i,]<-NULL
}
}
bomber<-function(x){
#filter out first five minutes  
#filter out predicted coordinates where the change is small given change in time is over 60*2 seconds.
#evaluate uncertainty
x$difflat<-x$uprlat-x$lwerlat
x$difflong<-x$uprlong-x$lwerlong
x$diffsum<-x$difflat+x$difflong
a<-head(sort(x$diffsum),2)
d<-data.frame(lat=NA,long=NA,sequence=c("first bomb","second bomb"),time=NA)
d[1,1]<-x[x$diffsum==a[1],]$latfit
d[1,2]<-x[x$diffsum==a[1],]$longfit
d[1,4]<-x[x$diffsum==a[1],]$timesincedpt
d[2,1]<-x[x$diffsum==a[2],]$latfit
d[2,2]<-x[x$diffsum==a[2],]$longfit
d[2,4]<-x[x$diffsum==a[2],]$timesincedpt
return(d)
}
#get a neat data frame with results
result<-cbind(bomber(predall),rep(dayconvt(day),2))
colnames(result)<-c("predicted latitude","predicted longitude","bomb sequence","Time of the Day","Day of the Week")

#convert time since departure to time of the day
result[1,4]<-as.character(as.POSIXct(testdata$features[[1]]$properties$time_long/1000+as.numeric(result$`Time of the Day`[1]),origin="1970-01-01",tz="MST"))
result[2,4]<-as.character(as.POSIXct(testdata$features[[1]]$properties$time_long/1000+as.numeric(result$`Time of the Day`[2]),origin="1970-01-01",tz="MST"))
print(result)
#visualization
#return 2 bomb coordinates with time in list
p1<-ggplot(predall,aes(x=latfit,y=longfit))+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10))+
  geom_smooth(data=subset(predall,latfit<46.8653))+
  geom_smooth(data=subset(predall,latfit>=46.8653&latfit<46.8683),col="red")+
  geom_smooth(data=subset(predall,latfit>=46.8683),se=F)+
  geom_smooth(data=subset(predall,latfit<46.8653),aes(x=latfit,y=lwerlong),lty="dashed")+
  geom_smooth(data=subset(predall,latfit>=46.8653&latfit<46.8683),aes(x=latfit,y=lwerlong),col="red",lty="dashed")+
  geom_smooth(data=subset(predall,latfit>=46.8683),aes(x=latfit,y=lwerlong),se=F,lty="dashed")+
  geom_smooth(data=subset(predall,latfit<46.8653),aes(x=latfit,y=uprlong),lty="dashed")+
  geom_smooth(data=subset(predall,latfit>=46.8653&latfit<46.8683),aes(x=latfit,y=uprlong),col="red",lty="dashed")+
  geom_smooth(data=subset(predall,latfit>=46.8683),aes(x=latfit,y=uprlong),se=F,lty="dashed")+
  coord_flip()
print(p1)
```


```{r}
#find out if the target moves faster | temperature
speed<-NA
for (i in 1:length(databak)){
  if(!is.null(databak[[i]]$properties$speed)){
  speed[i]<-databak[[i]]$properties$speed #convert ms to seconds, then convert it to "Montana UNIX" time
  }
  else {
    speed[i]<-NA
  }
}
timestampsa<-NA
for (i in 1:length(databak)){
  timestampsa[i]<-databak[[i]]$properties$time
}
longa<-NA
for (i in 1:length(databak)){
  longa[i]<-unlist(databak[[i]]$geometry$coordinates[1])
}
lata<-NA
for (i in 1:length(databak)){
  lata[i]<-unlist(databak[[i]]$geometry$coordinates[2])
}
timelonga<-NA
for (i in 1:length(databak)){
  timelonga[i]<-((databak[[i]]$properties$time_long/1000)-21600) #convert ms to seconds, then convert it to "Montana UNIX" time
}
sessions<-c(rep(1,length(data0$features)),rep(2,length(data1$features)),rep(3,length(data2$features)),rep(4,length(data3$features)),rep(5,length(data4$features)),rep(6,length(data5$features)),rep(7,length(data7$features)),rep(8,length(data8$features)),rep(9,length(data9$features)),rep(10,length(data10$features)))
databak<-data.frame(speed,longa,lata,timestampsa,timelonga,sessions)
databak<-na.omit(databak)
avggtr<-function(x){
  return(data.frame(mean(x$speed),sd(x$speed)))
}
stat<-cbind(ddply(databak,.(sessions),avggtr),c(65,63,57,61,54,60,55,55,56,34))
colnames(stat)<-c("sessions","average speed","standdard deviation","temperature")
stat<-stat[order(stat$temperature),]
stat
plot(stat$temperature,stat$`average speed`)
```



